language: java
install: "mvn install -DskipTests=true"
script:
  - "mvn -e clean test jacoco:report"
  - "bash <(curl -Ls https://coverage.codacy.com/get.sh)"
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
