language: java
install: "mvn install -DskipTests=true"
script:
  - "mvn -e clean test jacoco:report"
  - "bash <(curl -Ls https://coverage.codacy.com/get.sh)"
jdk:
  - openjdk8
  - openjdk11
  - openjdk14
  - oraclejdk11
  - oraclejdk14
